### ISSUE TITLE
Repeater: JWT4B tab disappearing 

### ISSUE THREAD

**Issue by calabacito** [ozzi-/JWT4B#41]
Hi ! 

In the repeater tab I have the JWT4B tab. 👍 
After playing in the tab (recalculate for ex), and then going to RAW the tab will disappear. 
This seems to be crashing, when I check Extender/extensions/JWT4B errror tab it shows:
_15:53:50.626 | [Ljava.lang.StackTraceElement;@f6c3b3e_

Also, after sending the request the tab disappear, and again the error tab show stacktraces. 

Thanks and keep the great work! 

pd: in Bapp store the extension seems outdated

**Comment by ozzi-** [comment]
Hi @calabacito 
I tried to reproduce your bug (Windows 10, Burp Community Edition v2020.4.1, JSON Web Tokens 1.9 from Bapp Store).
1. From Proxy History, send Request to Repeater
2. In Repater go to JWT4B Tab, recalculate signature
3. Go to Raw Tab and back to JWT4B tab
I get no errors and the tab is still there.

Ill try with the latest version here.

**Comment by ozzi-** [comment]
Note to self:
1.11 crashes as mentioned by calabacito. 

```
java.lang.RuntimeException: org.bouncycastle.util.encoders.DecoderException: unable to decode base64 string: String index out of range: 6
	at burp.r8.a(Unknown Source)
	at burp.e52.c(Unknown Source)
	at burp.bjp.a(Unknown Source)
	at burp.bjp.a(Unknown Source)
	at burp.bjp.lambda$new$0(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:442)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:293)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:143)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:74)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:646)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:621)
	at burp.bju.setSelectedIndex(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:4090)
	at java.desktop/javax.swing.plaf.synth.SynthTabbedPaneUI$1.mousePressed(SynthTabbedPaneUI.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6633)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at burp.bju.a(Unknown Source)
	at burp.bju.a(Unknown Source)
	at burp.gg3.mousePressed(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6633)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
Introduced with 3e213d798943594d1ad4d4fc0017a9128373ab0e

**Comment by ozzi-** [comment]
@calabacito  this seems only to happen, when don't enter a "valid" private key (i.E. MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCDG2/MGVVqOTV2E/NN7YP43JbFmsD2ZuFDxgXhERv+0Eg== is valid).  I patched it to output the error and to continue instead of crashing ;)

![screenshot](https://i.imgur.com/FgYVob3.png)


Can you test this and give me feedback?
[jwt4b.zip](https://github.com/ozzi-/JWT4B/files/4716959/jwt4b.zip)

Cheers

**Comment by calabacito** [comment]
- Recalculate signature fixed! 

But:

1. - From Proxy History, send Request to Repeater
2. - In Repater go to JWT4B Tab, **change alg None Attack**
3. - Go to Raw Tab. 
4. - crash

Seems to be happening also when playing around with modified **wrong** text, and playing with the options.
Ex: 
`Headers = {
  "alg" : "HS256"a,
  "typ" : "JWS"
}`

Thanks for the quick response!

**Comment by ozzi-** [comment]
Hi @calabacito 
Great to hear!

Thanks , I couldn't reporduce the alg attack, however the one with the invalid JSON.
I pushed a fix, please check :)

I uploaded a JAR or compile via maven.

Regards

[JWT4B_fix.zip](https://github.com/ozzi-/JWT4B/files/4736287/JWT4B_fix.zip)

**Comment by ozzi-** [comment]
3fe958d one to slay them all. if not, please reopen :D
